### ISSUE TITLE
Todo list for release 1.2.0

### ISSUE THREAD

**Issue by jobe-m** [jobe-m/ownkeepass#8]
- [x] Adjust top margin on edit item icon dialog
- [x] Close master groups page again if password was wrong (regression)
- [x] Disable "Edit password entry" on show entry page (Keepass 2 database)
- [x] Implement saving of new icon for password entries in Keepass 2 database
- [x] Add change icon in Edit password entry dialog
- [x] Create translation request on transifex
- [x] Implement loading of custom database icons for Keepass 2 database
- [x] Implement loading and saving of custom database icons for Keepass 1 database
- [x] Create alpha channel fading image for icon background with inkscape
- [x] Adjust edit item icon dialog for jolla tablet
- [x] Update translations
- [x] Update about and changelog page
- [x] Fix layout for landscape format of fast unlock page on tablet

**Comment by jobe-m** [comment]
- [x] Update the flattr url on the about page

**Comment by jobe-m** [comment]
Fix bug "Internal database error" when creating new password group in Keepass 2 database
- [x] conversion of QString to Uuid failed

**Comment by jobe-m** [comment]
Release 1.2.0 published on openrepos
