### ISSUE TITLE
[TODO] Implementing write support for Keepass 2

### ISSUE THREAD

**Issue by jobe-m** [jobe-m/ownkeepass#9]
- [x] Changing icon of password entry with click on icon in list view does not save the new icon
- [x] Additional key-values of Keepass 2 entries are not shown in the entry view
- [x] Move dialog does not show icons of the password groups
- [x] Update password field on generate password dialog 
- [x] Update password field on main page
- [x] Update password field on *create new* and *open existing* Keepass database
- [x] The 4 image buttons on the generate password dialog page does not scale on higher screen resolutions
- [x] When pressing on *Nothing selected yet  >* to open the file browser no visual indication appears to show that the element was selected
- [x] On ShowEntryDetailsPage: Long press on URL, Username, Password, Comment and any of the additional attributes should open a context menu with *Copy* (to clipboard)
- [x] Bug: App Cover does not show username and password

**Comment by jobe-m** [comment]
Feature request for clickable URLs:
- [x] onClicked: Qt.openUrlExternally(text) in line 167 of ShowEntryDetailsPage.qml

**Comment by jobe-m** [comment]
- [x] Bugfix: Disable adding additional Attributes for Keepass 1 database
- [x] Check if additional Attribute is saved with only set key and empty text value

**Comment by jobe-m** [comment]
Just update of about and changelog page and new translations missing
